/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as RequestQuoteRouteImport } from './routes/request-quote'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as MarketInsightsRouteImport } from './routes/market-insights'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as GoldInUgandaRouteImport } from './routes/gold-in-uganda'
import { Route as GoldInTanzaniaRouteImport } from './routes/gold-in-tanzania'
import { Route as GoldInKenyaRouteImport } from './routes/gold-in-kenya'
import { Route as GoldInCongoRouteImport } from './routes/gold-in-congo'
import { Route as GoldInAfricaRouteImport } from './routes/gold-in-africa'
import { Route as GlobalDeliveryRouteImport } from './routes/global-delivery'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as ExportDocumentationRouteImport } from './routes/export-documentation'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestQuoteRoute = RequestQuoteRouteImport.update({
  id: '/request-quote',
  path: '/request-quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketInsightsRoute = MarketInsightsRouteImport.update({
  id: '/market-insights',
  path: '/market-insights',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const GoldInUgandaRoute = GoldInUgandaRouteImport.update({
  id: '/gold-in-uganda',
  path: '/gold-in-uganda',
  getParentRoute: () => rootRouteImport,
} as any)
const GoldInTanzaniaRoute = GoldInTanzaniaRouteImport.update({
  id: '/gold-in-tanzania',
  path: '/gold-in-tanzania',
  getParentRoute: () => rootRouteImport,
} as any)
const GoldInKenyaRoute = GoldInKenyaRouteImport.update({
  id: '/gold-in-kenya',
  path: '/gold-in-kenya',
  getParentRoute: () => rootRouteImport,
} as any)
const GoldInCongoRoute = GoldInCongoRouteImport.update({
  id: '/gold-in-congo',
  path: '/gold-in-congo',
  getParentRoute: () => rootRouteImport,
} as any)
const GoldInAfricaRoute = GoldInAfricaRouteImport.update({
  id: '/gold-in-africa',
  path: '/gold-in-africa',
  getParentRoute: () => rootRouteImport,
} as any)
const GlobalDeliveryRoute = GlobalDeliveryRouteImport.update({
  id: '/global-delivery',
  path: '/global-delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportDocumentationRoute = ExportDocumentationRouteImport.update({
  id: '/export-documentation',
  path: '/export-documentation',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/compliance': typeof ComplianceRoute
  '/contact': typeof ContactRoute
  '/export-documentation': typeof ExportDocumentationRoute
  '/faqs': typeof FaqsRoute
  '/gallery': typeof GalleryRoute
  '/global-delivery': typeof GlobalDeliveryRoute
  '/gold-in-africa': typeof GoldInAfricaRoute
  '/gold-in-congo': typeof GoldInCongoRoute
  '/gold-in-kenya': typeof GoldInKenyaRoute
  '/gold-in-tanzania': typeof GoldInTanzaniaRoute
  '/gold-in-uganda': typeof GoldInUgandaRoute
  '/industries': typeof IndustriesRoute
  '/market-insights': typeof MarketInsightsRoute
  '/products': typeof ProductsRoute
  '/request-quote': typeof RequestQuoteRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/compliance': typeof ComplianceRoute
  '/contact': typeof ContactRoute
  '/export-documentation': typeof ExportDocumentationRoute
  '/faqs': typeof FaqsRoute
  '/gallery': typeof GalleryRoute
  '/global-delivery': typeof GlobalDeliveryRoute
  '/gold-in-africa': typeof GoldInAfricaRoute
  '/gold-in-congo': typeof GoldInCongoRoute
  '/gold-in-kenya': typeof GoldInKenyaRoute
  '/gold-in-tanzania': typeof GoldInTanzaniaRoute
  '/gold-in-uganda': typeof GoldInUgandaRoute
  '/industries': typeof IndustriesRoute
  '/market-insights': typeof MarketInsightsRoute
  '/products': typeof ProductsRoute
  '/request-quote': typeof RequestQuoteRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/compliance': typeof ComplianceRoute
  '/contact': typeof ContactRoute
  '/export-documentation': typeof ExportDocumentationRoute
  '/faqs': typeof FaqsRoute
  '/gallery': typeof GalleryRoute
  '/global-delivery': typeof GlobalDeliveryRoute
  '/gold-in-africa': typeof GoldInAfricaRoute
  '/gold-in-congo': typeof GoldInCongoRoute
  '/gold-in-kenya': typeof GoldInKenyaRoute
  '/gold-in-tanzania': typeof GoldInTanzaniaRoute
  '/gold-in-uganda': typeof GoldInUgandaRoute
  '/industries': typeof IndustriesRoute
  '/market-insights': typeof MarketInsightsRoute
  '/products': typeof ProductsRoute
  '/request-quote': typeof RequestQuoteRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/compliance'
    | '/contact'
    | '/export-documentation'
    | '/faqs'
    | '/gallery'
    | '/global-delivery'
    | '/gold-in-africa'
    | '/gold-in-congo'
    | '/gold-in-kenya'
    | '/gold-in-tanzania'
    | '/gold-in-uganda'
    | '/industries'
    | '/market-insights'
    | '/products'
    | '/request-quote'
    | '/services'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/compliance'
    | '/contact'
    | '/export-documentation'
    | '/faqs'
    | '/gallery'
    | '/global-delivery'
    | '/gold-in-africa'
    | '/gold-in-congo'
    | '/gold-in-kenya'
    | '/gold-in-tanzania'
    | '/gold-in-uganda'
    | '/industries'
    | '/market-insights'
    | '/products'
    | '/request-quote'
    | '/services'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/compliance'
    | '/contact'
    | '/export-documentation'
    | '/faqs'
    | '/gallery'
    | '/global-delivery'
    | '/gold-in-africa'
    | '/gold-in-congo'
    | '/gold-in-kenya'
    | '/gold-in-tanzania'
    | '/gold-in-uganda'
    | '/industries'
    | '/market-insights'
    | '/products'
    | '/request-quote'
    | '/services'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ComplianceRoute: typeof ComplianceRoute
  ContactRoute: typeof ContactRoute
  ExportDocumentationRoute: typeof ExportDocumentationRoute
  FaqsRoute: typeof FaqsRoute
  GalleryRoute: typeof GalleryRoute
  GlobalDeliveryRoute: typeof GlobalDeliveryRoute
  GoldInAfricaRoute: typeof GoldInAfricaRoute
  GoldInCongoRoute: typeof GoldInCongoRoute
  GoldInKenyaRoute: typeof GoldInKenyaRoute
  GoldInTanzaniaRoute: typeof GoldInTanzaniaRoute
  GoldInUgandaRoute: typeof GoldInUgandaRoute
  IndustriesRoute: typeof IndustriesRoute
  MarketInsightsRoute: typeof MarketInsightsRoute
  ProductsRoute: typeof ProductsRoute
  RequestQuoteRoute: typeof RequestQuoteRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-quote': {
      id: '/request-quote'
      path: '/request-quote'
      fullPath: '/request-quote'
      preLoaderRoute: typeof RequestQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market-insights': {
      id: '/market-insights'
      path: '/market-insights'
      fullPath: '/market-insights'
      preLoaderRoute: typeof MarketInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gold-in-uganda': {
      id: '/gold-in-uganda'
      path: '/gold-in-uganda'
      fullPath: '/gold-in-uganda'
      preLoaderRoute: typeof GoldInUgandaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gold-in-tanzania': {
      id: '/gold-in-tanzania'
      path: '/gold-in-tanzania'
      fullPath: '/gold-in-tanzania'
      preLoaderRoute: typeof GoldInTanzaniaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gold-in-kenya': {
      id: '/gold-in-kenya'
      path: '/gold-in-kenya'
      fullPath: '/gold-in-kenya'
      preLoaderRoute: typeof GoldInKenyaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gold-in-congo': {
      id: '/gold-in-congo'
      path: '/gold-in-congo'
      fullPath: '/gold-in-congo'
      preLoaderRoute: typeof GoldInCongoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gold-in-africa': {
      id: '/gold-in-africa'
      path: '/gold-in-africa'
      fullPath: '/gold-in-africa'
      preLoaderRoute: typeof GoldInAfricaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/global-delivery': {
      id: '/global-delivery'
      path: '/global-delivery'
      fullPath: '/global-delivery'
      preLoaderRoute: typeof GlobalDeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export-documentation': {
      id: '/export-documentation'
      path: '/export-documentation'
      fullPath: '/export-documentation'
      preLoaderRoute: typeof ExportDocumentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ComplianceRoute: ComplianceRoute,
  ContactRoute: ContactRoute,
  ExportDocumentationRoute: ExportDocumentationRoute,
  FaqsRoute: FaqsRoute,
  GalleryRoute: GalleryRoute,
  GlobalDeliveryRoute: GlobalDeliveryRoute,
  GoldInAfricaRoute: GoldInAfricaRoute,
  GoldInCongoRoute: GoldInCongoRoute,
  GoldInKenyaRoute: GoldInKenyaRoute,
  GoldInTanzaniaRoute: GoldInTanzaniaRoute,
  GoldInUgandaRoute: GoldInUgandaRoute,
  IndustriesRoute: IndustriesRoute,
  MarketInsightsRoute: MarketInsightsRoute,
  ProductsRoute: ProductsRoute,
  RequestQuoteRoute: RequestQuoteRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
